import type { LectureSession, ExportOptions, TranscriptSegment } from '../../types';

export interface TemplateData {
  title: string;
  metadata: {
    date: string;
    duration: string;
    wordCount: number;
    language: string;
    cost: string;
    exportDate: string;
    layout: string;
  };
  segments: {
    timestamp?: string;
    text: string;
    speaker?: string;
    language?: string;
  }[];
  summary?: string;
  branding: {
    appName: string;
    logoUrl?: string;
    watermark?: string;
  };
}

export class TemplateEngine {
  static generateTemplateData(
    session: LectureSession,
    filteredSegments: TranscriptSegment[],
    options: ExportOptions
  ): TemplateData {
    const { includeTimestamps, layout = 'professional' } = options;

    // Format metadata
    const startDate = new Date(session.startTime).toLocaleString('zh-HK', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZone: 'Asia/Hong_Kong'
    });

    const duration = this.formatDuration(session.duration);
    const wordCount = session.segments.reduce((acc, seg) => acc + seg.text.split(' ').length, 0);
    const languageMap = {
      'zh': '中文',
      'en': 'English',
      'mixed': '中英文混合'
    };

    // Process segments
    const segments = filteredSegments.map(segment => ({
      timestamp: includeTimestamps ? this.formatTimestamp(segment.timestamp) : undefined,
      text: segment.text.trim(),
      speaker: segment.speaker,
      language: segment.language
    }));

    return {
      title: session.name,
      metadata: {
        date: startDate,
        duration,
        wordCount,
        language: languageMap[session.language] || session.language,
        cost: `$${session.cost.toFixed(4)}`,
        exportDate: new Date().toLocaleString('zh-HK', { timeZone: 'Asia/Hong_Kong' }),
        layout
      },
      segments,
      summary: session.summary,
      branding: {
        appName: 'Lecture Transcription PWA',
        watermark: options.includeWatermark ? 'Generated by Lecture Transcription PWA for Hong Kong Universities' : undefined
      }
    };
  }

  private static formatDuration(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const remainingSeconds = Math.floor(seconds % 60);

    if (hours > 0) {
      return `${hours}:${minutes.toString().padStart(2, '0')}:${remainingSeconds.toString().padStart(2, '0')}`;
    }
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  }

  private static formatTimestamp(seconds: number): string {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.floor(seconds % 60);
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
  }

  // Academic paper style template
  static getAcademicTemplate(): string {
    return `
<!DOCTYPE html>
<html lang="zh-HK">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@300;400;500;700&family=Inter:wght@300;400;500;600;700&display=swap');

        body {
            font-family: 'Noto Sans TC', 'Inter', sans-serif;
            line-height: 1.8;
            margin: 0;
            padding: 40px;
            background: #fff;
            color: #333;
            max-width: 210mm;
            margin: 0 auto;
        }

        .header {
            text-align: center;
            border-bottom: 3px solid #1a73e8;
            padding-bottom: 20px;
            margin-bottom: 40px;
        }

        .title {
            font-size: 24px;
            font-weight: 700;
            color: #1a73e8;
            margin: 0 0 10px 0;
            letter-spacing: 0.5px;
        }

        .subtitle {
            font-size: 14px;
            color: #666;
            font-weight: 400;
        }

        .metadata {
            background: #f8f9fa;
            border-left: 4px solid #1a73e8;
            padding: 20px;
            margin-bottom: 30px;
            border-radius: 0 8px 8px 0;
        }

        .metadata-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
        }

        .metadata-item {
            display: flex;
            justify-content: space-between;
            padding: 5px 0;
            border-bottom: 1px dotted #ddd;
        }

        .metadata-label {
            font-weight: 600;
            color: #555;
        }

        .section-title {
            font-size: 18px;
            font-weight: 600;
            color: #333;
            margin: 30px 0 20px 0;
            padding: 10px 0;
            border-bottom: 2px solid #e0e0e0;
        }

        .transcript-content {
            margin: 20px 0;
        }

        .transcript-segment {
            margin: 15px 0;
            padding: 10px 0;
            border-bottom: 1px solid #f0f0f0;
        }

        .timestamp {
            display: inline-block;
            background: #e3f2fd;
            color: #1565c0;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 500;
            margin-right: 10px;
            font-family: 'Inter', monospace;
        }

        .speaker {
            font-weight: 600;
            color: #d32f2f;
            margin-right: 5px;
        }

        .summary {
            background: linear-gradient(135deg, #e8f5e8, #f0f8ff);
            border: 1px solid #81c784;
            border-radius: 12px;
            padding: 25px;
            margin: 30px 0;
        }

        .summary-title {
            font-size: 16px;
            font-weight: 600;
            color: #2e7d32;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
        }

        .summary-title::before {
            content: "📋";
            margin-right: 8px;
        }

        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            text-align: center;
            color: #666;
            font-size: 12px;
        }

        .watermark {
            color: #ccc;
            font-style: italic;
        }

        @media print {
            body { margin: 0; padding: 20mm; }
            .timestamp { background: #f5f5f5 !important; color: #333 !important; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{{title}}</h1>
        <div class="subtitle">講座逐字稿 | Lecture Transcript</div>
    </div>

    {{#metadata}}
    <div class="metadata">
        <div class="metadata-grid">
            <div class="metadata-item">
                <span class="metadata-label">日期 Date:</span>
                <span>{{date}}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">時長 Duration:</span>
                <span>{{duration}}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">字數 Word Count:</span>
                <span>{{wordCount}} words</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">語言 Language:</span>
                <span>{{language}}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">成本 Cost:</span>
                <span>{{cost}}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">導出日期 Export Date:</span>
                <span>{{exportDate}}</span>
            </div>
        </div>
    </div>
    {{/metadata}}

    {{#summary}}
    <div class="summary">
        <div class="summary-title">講座摘要 Summary</div>
        <div>{{{summary}}}</div>
    </div>
    {{/summary}}

    <h2 class="section-title">完整逐字稿 Full Transcript</h2>
    <div class="transcript-content">
        {{#segments}}
        <div class="transcript-segment">
            {{#timestamp}}<span class="timestamp">{{timestamp}}</span>{{/timestamp}}
            {{#speaker}}<span class="speaker">{{speaker}}:</span>{{/speaker}}
            <span>{{text}}</span>
        </div>
        {{/segments}}
    </div>

    <div class="footer">
        <div>{{branding.appName}}</div>
        {{#branding.watermark}}
        <div class="watermark">{{branding.watermark}}</div>
        {{/branding.watermark}}
    </div>
</body>
</html>`;
  }

  // Professional meeting notes template
  static getProfessionalTemplate(): string {
    return `
<!DOCTYPE html>
<html lang="zh-HK">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600;700&display=swap');

        body {
            font-family: 'Noto Sans TC', 'Inter', sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 30px;
            background: #fafafa;
            color: #333;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }

        .title {
            font-size: 28px;
            font-weight: 700;
            margin: 0;
            text-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .content {
            padding: 30px;
        }

        .info-card {
            background: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 25px;
            border-left: 4px solid #667eea;
        }

        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
        }

        .info-item {
            text-align: center;
            padding: 10px;
        }

        .info-value {
            font-size: 18px;
            font-weight: 600;
            color: #667eea;
            display: block;
        }

        .info-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 5px;
        }

        .section {
            margin: 30px 0;
        }

        .section-header {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #e9ecef;
        }

        .section-icon {
            font-size: 24px;
            margin-right: 10px;
        }

        .section-title {
            font-size: 20px;
            font-weight: 600;
            color: #495057;
            margin: 0;
        }

        .transcript-item {
            background: #fff;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 10px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        }

        .timestamp {
            background: #667eea;
            color: white;
            padding: 4px 8px;
            border-radius: 20px;
            font-size: 11px;
            font-weight: 500;
            display: inline-block;
            margin-right: 10px;
        }

        .summary-box {
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            border-radius: 12px;
            padding: 25px;
            margin: 25px 0;
        }

        .summary-header {
            font-size: 18px;
            font-weight: 600;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
        }

        .summary-content {
            line-height: 1.7;
        }

        .footer {
            background: #f8f9fa;
            padding: 20px;
            text-align: center;
            color: #6c757d;
            border-top: 1px solid #e9ecef;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 class="title">{{title}}</h1>
        </div>

        <div class="content">
            {{#metadata}}
            <div class="info-card">
                <div class="info-grid">
                    <div class="info-item">
                        <span class="info-value">{{date}}</span>
                        <div class="info-label">Date 日期</div>
                    </div>
                    <div class="info-item">
                        <span class="info-value">{{duration}}</span>
                        <div class="info-label">Duration 時長</div>
                    </div>
                    <div class="info-item">
                        <span class="info-value">{{wordCount}}</span>
                        <div class="info-label">Words 字數</div>
                    </div>
                    <div class="info-item">
                        <span class="info-value">{{language}}</span>
                        <div class="info-label">Language 語言</div>
                    </div>
                </div>
            </div>
            {{/metadata}}

            {{#summary}}
            <div class="summary-box">
                <div class="summary-header">
                    <span class="section-icon">📋</span>
                    Lecture Summary 講座摘要
                </div>
                <div class="summary-content">{{{summary}}}</div>
            </div>
            {{/summary}}

            <div class="section">
                <div class="section-header">
                    <span class="section-icon">🎙️</span>
                    <h2 class="section-title">Full Transcript 完整逐字稿</h2>
                </div>

                {{#segments}}
                <div class="transcript-item">
                    {{#timestamp}}<span class="timestamp">{{timestamp}}</span>{{/timestamp}}
                    {{#speaker}}<strong>{{speaker}}:</strong> {{/speaker}}
                    {{text}}
                </div>
                {{/segments}}
            </div>
        </div>

        <div class="footer">
            Generated by {{branding.appName}}
            {{#branding.watermark}}<br><em>{{branding.watermark}}</em>{{/branding.watermark}}
        </div>
    </div>
</body>
</html>`;
  }

  // Clean minimal template
  static getCleanTemplate(): string {
    return `
<!DOCTYPE html>
<html lang="zh-HK">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <style>
        body {
            font-family: 'SF Pro Text', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans TC', sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 40px 20px;
            color: #333;
            max-width: 700px;
            margin: 0 auto;
        }

        .title {
            font-size: 32px;
            font-weight: 300;
            margin-bottom: 40px;
            text-align: center;
            color: #2c3e50;
        }

        .meta {
            font-size: 14px;
            color: #7f8c8d;
            margin-bottom: 40px;
            text-align: center;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 6px;
        }

        .summary {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 20px;
            margin: 30px 0;
            font-style: italic;
        }

        .transcript p {
            margin: 20px 0;
            padding: 10px 0;
        }

        .time {
            color: #6c757d;
            font-family: monospace;
            font-size: 12px;
            margin-right: 15px;
        }

        .footer {
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #ecf0f1;
            text-align: center;
            font-size: 12px;
            color: #95a5a6;
        }
    </style>
</head>
<body>
    <h1 class="title">{{title}}</h1>

    {{#metadata}}
    <div class="meta">
        {{date}} • {{duration}} • {{wordCount}} words • {{language}}
    </div>
    {{/metadata}}

    {{#summary}}
    <div class="summary">
        <strong>Summary:</strong> {{{summary}}}
    </div>
    {{/summary}}

    <div class="transcript">
        {{#segments}}
        <p>
            {{#timestamp}}<span class="time">{{timestamp}}</span>{{/timestamp}}
            {{text}}
        </p>
        {{/segments}}
    </div>

    <div class="footer">
        {{branding.appName}}
        {{#branding.watermark}}<br>{{branding.watermark}}{{/branding.watermark}}
    </div>
</body>
</html>`;
  }
}